### ISSUE TITLE
修改了固定链接之后,所有页面均打开404界面

### ISSUE THREAD

**Issue by FrankWang117** [bizhongbio/bizhongbio#2]
??

**Comment by bizhong** [comment]
本主题使用了 Baidu CDN 加载 Font Awesome 字体图标，会导致“加载资源失败”。本地出现问题，还是正式出现问题？

**Comment by FrankWang1991** [comment]
是搭建在服务器上的时候出现的问题。好像是因为我更换了wordpress的连接的问题




| |
王森
前端工程师
|
|
15301012136
邮箱：wsgoodman@163.com
605454989
前端小学生
|

签名由 网易邮箱大师 定制

在2017年12月22日 20:42，兰必钟 写道：

本主题使用了 Baidu CDN 加载 Font Awesome 字体图标，会导致“加载资源失败”。本地出现问题，还是正式出现问题？

**Comment by bizhong** [comment]
哈哈

**Comment by FrankWang1991** [comment]
?? 啥子事情哦 干嘛要笑啊
